workspace:
  base: /srv/app
  path: src/github.com/appleboy/drone-git-push

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    secrets: [ codecov_token ]
    commands:
      - make vet
      - make lint
      - make test
      - make build
      # build binary for docker image
      - make static_build
    when:
      event: [ push, tag, pull_request ]

  release:
    image: appleboy/golang-testing
    pull: true
    environment:
      TAGS: netgo
      GOPATH: /srv/app
    commands:
      - make release
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false

  publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false

  publish_latest:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ 'latest' ]
    secrets: [ docker_username, docker_password ]
    when:
      event: [ push ]
      branch: [ master ]
      local: false

  release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - dist/release/*
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]
      local: false
