workspace:
  base: /go/src
  path: github.com/appleboy/drone-git-push

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  test:
    image: appleboy/golang-testing
    pull: true
    secrets: [ codecov_token ]
    commands:
      - make vet
      - make lint
      - make test
      - make build
      - make misspell-check
      - make test-vendor

  build_linux_amd64:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_amd64

  build_linux_i386:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_i386

  build_linux_arm64:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_arm64

  build_linux_arm:
    image: golang:1.10
    pull: true
    group: build
    commands:
      - make build_linux_arm

  # codecov:
  #   image: robertstettner/drone-codecov
  #   secrets: [ codecov_token ]
  #   files:
  #     - .cover/coverage.txt
  #   when:
  #     event: [ push, pull_request ]

  publish_linux_amd64:
    image: plugins/docker
    repo: appleboy/drone-git-push
    tags: [ latest ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  # publish_linux_arm64:
  #   image: plugins/docker
  #   repo: appleboy/drone-git-push
  #   tags: [ linux-arm64 ]
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: Dockerfile.arm64
  #   when:
  #     branch: master
  #     event: push

  # publish_linux_arm:
  #   image: plugins/docker
  #   repo: appleboy/drone-git-push
  #   tags: [ linux-arm ]
  #   secrets: [ docker_username, docker_password ]
  #   dockerfile: Dockerfile.arm
  #   when:
  #     branch: master
  #     event: push

  release:
    image: appleboy/golang-testing
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  publish_tag:
    image: plugins/docker
    repo: ${DRONE_REPO}
    tags: [ '${DRONE_TAG}' ]
    secrets: [ docker_username, docker_password ]
    group: release
    when:
      event: [ tag ]
      local: false

  release_tag:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false
